RingbitCar.init_wheel(AnalogPin.P1, AnalogPin.P2)
RingbitCar.forward()
let Strip = neopixel.create(DigitalPin.P0, 24, NeoPixelMode.RGB)
basic.forever(function () {
    Strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(100)
    Strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(100)
    Strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(100)
    Strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(100)
    Strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(100)
})
